ares.components += m68000
ares.components += z80
ares.components += arm7tdmi

ares.objects += ares-pgm-cartridge
ares.objects += ares-pgm-cpu
ares.objects += ares-pgm-igs023
ares.objects += ares-pgm-system

$(object.path)/ares-pgm-cartridge.o:  $(ares.path)/pgm/cartridge/cartridge.cpp
$(object.path)/ares-pgm-cpu.o:        $(ares.path)/pgm/cpu/cpu.cpp
$(object.paht)/ares-pgm-igs023.o:     $(ares.path)/pgm/igs023/igs023.cpp
$(object.path)/ares-pgm-system.o:     $(ares.path)/pgm/system/system.cpp
